[package]
name = "ui-dioxus"
version = "0.1.0"
authors = ["Daniel Mason <daniel.mason@dsit.gov.uk>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = [] }
data-models = { workspace = true }
serde = { workspace = true, features = ["derive"] }
yaml_serde = { workspace = true }

[dev-dependencies]
data-models = { workspace = true, features = ["test-utils"] }
rand = { workspace = true }

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
